name: Deploy to Prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.12.1'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION || 'us-east-1' }}

      - name: Install Dotenv CLI
        run: sudo npm install -g dotenv-cli --force

      - name: Install AWS CDK
        run: sudo npm install -g aws-cdk

      - name: Install App Dependencies
        run: npm install
        working-directory: frontend

      - name: Build App
        run: npm run build
        working-directory: frontend

      - name: Install CDK Dependencies
        run: npm install
        working-directory: iac
      
      - name: Remove CDK cache
        run: rm -rf cdk.out
        working-directory: iac

      - name: Deploy CDK Stack
        run: npm run deploy:prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: iac
